name: "Dart Code Metrics Action"
description: "A GitHub action to perform Dart Code Metrics checks automatically."
author: "Dart Code Checker team"

branding:
  color: "blue"
  icon: "search"

inputs:
  check_unused_files:
    description: "Additional scan for find unused files in package."
    required: false
    default: "false"
  github_token:
    description: "Token to connect to GitHub. Use secrets.GITHUB_TOKEN."
    required: true
  github_pat:
    description: "Personal access token. Required if you had private GitHub repository in the package dependencies."
    required: false
    default: ""
  folders:
    description: "List of folders whose contents will be scanned."
    required: false
    default: "lib"
  relative_path:
    description: "Path of the package relatively to the root of the repository."
    required: false
    default: ""
  analyze_report_title_pattern:
    description: "Configurable analyze report title pattern."
    required: false
    default: "Dart Code Metrics analyze report of $packageName"
  unused_files_report_title_pattern:
    description: "Configurable unused files report title pattern."
    required: false
    default: "Dart Code Metrics unused files report of $packageName"

runs:
  using: "docker"
  image: "Dockerfile"
