name: Update Docker image

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/update_docker_image.yaml"
      - "action_app/**"
      - "scripts/Dockerfile"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/update_docker_image.yaml"
      - "action_app/**"
      - "scripts/Dockerfile"

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      TAG: v2
      DOCKERFILE: "scripts/Dockerfile"
      IMAGE: dkrutskikh/dart_code_metrics_action_wip

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Build new image
        run: sudo docker build -f $DOCKERFILE -t $IMAGE:$TAG .

      - name: Push new image
        env:
          DOCKER_USERNAME: dkrutskikh
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo $DOCKER_TOKEN | sudo docker login --username=$DOCKER_USERNAME --password-stdin
          sudo docker push $IMAGE:$TAG
